export const HKSoccerPrincipalMkts = [
    "Clean Sheet",
    "Score In Both Halves",
    "Team Not to Score",
    "To Win To Nil",
    "Win Both Halves",
    "Away Team Goals (Bands)",
    "Double Chance",
    "First Goal Time (30 Minute Intervals)",
    "First Team To Score",
    "Half With Most Goals",
    "Half-time Away Team Total Goals (Bands)",
    "Half-time Double Chance",
    "Half-time First Team To Score",
    "Half-time Handicap With Tie",
    "Half-time Home Team Total Goals (Bands)",
    "Half-time Result",
    "Half-time Total Goals (Bands)",
    "Handicap With Tie",
    "Last Team To Score",
    "Match Result",
    "Second Half Double Chance",
    "Second Half First Team To Score",
    "Second Half Handicap",
    "Second Half Result",
    "Corners Handicap With Tie",
    "Result After 05 Minutes",
    "Result After 10 Minutes",
    "Result After 15 Minutes",
    "Result After 20 Minutes",
    "Result After 25 Minutes",
    "Result After 30 Minutes",
    "Result After 35 Minutes",
    "Result After 40 Minutes",
    "Result After 50 Minutes",
    "Result After 55 Minutes",
    "Result After 60 Minutes",
    "Result After 65 Minutes",
    "Result After 70 Minutes",
    "Result After 75 Minutes",
    "Result After 80 Minutes",
    "Result After 85 Minutes",
    "Team With Most Corners",
    "Second Half Away Team Total Goals (Bands)",
    "Second Half Home Team Total Goals (Bands)",
    "Second Half Total Goals (Bands)",
    "Bookings Points Handicap With Tie",
    "First Carded Team",
    "Team With Most Bookings Points",
    "Total Cards (Bands)",
    "Both Teams To Score and Total Goals Over / Under",
    "Total Goals (Bands)",
    "Which Team to Score",
    "Away Team Corners (Bands)",
    "Home Team Corners (Bands)",
    "Second Half Away Team Exact Number of Goals",
    "Second Half Home Team Exact Number of Goals",
    "Half-time Total Corners",
    "Half-time Away Team Exact Number of Goals",
    "Half-time Home Team Exact Number of Goals",
    "Total Bookings Points (Bands)",
    "Double Chance & Both Teams To Score",
    "Double Chance & Over/Under",
    "Half Time Result and Both Teams To Score",
    "Half-time Double Chance and Both Teams To Score",
    "Half-time Double Chance and Total Goals Over / Under",
    "Half-time Exact Number of Goals",
    "Half-time Result and Total Goals Over / Under",
    "Match Result and Both Teams To Score",
    "Match Result and Total Goals Over / Under",
    "Second Half Double Chance and Both Teams To Score",
    "Second Half Double Chance and Total Goals Over / Under",
    "Second Half Result and Both Teams to Score",
    "Second Half Result and Total Goals Over / Under",
    "Second Half Exact Number of Goals",
    "Half-time Away Team Exact Number of Corners",
    "Half-time Home Team Exact Number of Corners",
    "Match Result and First Team To Score",
    "Second Half Winning Margin",
    "Half-time / Full Time",
    "First Goal Time (10 Minute Intervals)",
    "AAMS Second Half Correct Score",
    "Away Team Exact Number of Goals",
    "Correct Score",
    "Exact Number of Goals",
    "Half-time Correct Score",
    "Half-time Winning Margin",
    "Home Team Exact Number of Goals",
    "Home Team Goals (Bands)",
    "Second Half Correct Score",
    "Anytime GoalScorer",
    "Away Team First GoalScorer",
    "First GoalScorer",
    "Home Team First GoalScorer",
    "Last GoalScorer",
    "Player To Score A Hat Trick",
    "Player To Score Two Or More Goals",
    "Winning Margin",
    "No Draw Both Teams To Score",
    "Next Team to Score in the Next Minute (1 Minute intervals)",
    "Next Carded Team in the Next Minute (1 Minute intervals)",
    "Most Carded Team in the Next Minute (1 Minute intervals)",
    "Match Result in the Next Minute (1 Minute intervals)",
    "Next Corner Team in the Next Minute (1 Minute intervals)",
    "Team With Most Corners in the Next Minute (1 Minute intervals)",
    "Half-time Next Team To Score",
    "Half-time Corner Handicap",
    "Rest of First Half Result",
    "Half-time Most Corners Team (With Draw)",
    "Next Corner Team",
    "Next Team To Score",
    "Extra Time Half-time Result (excluding normal time goals)",
    "Result At Extra Time Half-time (including normal time goals)",
    "Match Result After Extra Time (including normal time goals)",
    "Rest of Match Result",
    "Result After 5 Minutes",
    "Next Team to Score in the Next 5 Minutes (5 Minute intervals)",
    "Most Carded Team in the Next 5 Minutes (5 Minute intervals)",
    "Next Carded Team in the Next 5 Minutes (5 Minute intervals)",
    "Match Result in the Next 5 Minutes (5 Minute intervals)",
    "Team With Most Corners in the Next 5 Minutes (5 Minute intervals)",
    "Next Carded Team",
    "Total Corners",
    "Next Home Goal Time",
    "Next Away Goal Time",
    "Next Goal Time",
    "Asian Handicap",
    "Half-time Exact Number of Cards",
    "Next Home Team GoalScorer",
    "Next Away Team GoalScorer",
    "Next GoalScorer",
    "Extra Time Half-time Correct Score (excluding normal time goals)",
    "Correct Score At Extra Time Half-time (including normal time goals)",
    "Extra Time Correct Score (excluding normal time goals)",
    "Correct Score After Extra Time (including normal time goals)",
    "Exact Number of Cards",
    "Next Away Penalty to be Scored Yes/No",
    "Extra Time Half-time Asian Handicap (excluding normal time goals)",
    "Asian Handicap At Extra Time Half-time (including normal time goals)",
    "Extra Time Half-time Total Goals Over/Under (excluding normal time goals)",
    "Total Goals At Extra Time Half-time Over/Under (including normal time goals)",
    "Extra Time Next Team To Score (including normal time goals)",
    "Extra Time Next Team to Score (excluding normal time goals)",
    "Extra Time Asian Handicap (excluding normal time goals)",
    "Asian Handicap After Extra Time (including normal time goals)",
    "Total Goals After Extra Time Over/Under (including normal time goals)",
    "Extra Time Result (excluding normal time goals)",
    "Extra Time Total Goals Over/Under (excluding normal time goals)",
    "How Will the Tie Be Decided"
];

export const HKBasketballPrincipalMkts = [
    "Money Line",
    "1st Half Money Line",
    "1st Quarter Money Line",
    "2nd Quarter Money Line",
    "3rd Quarter Money Line",
    "4th Quarter Money Line",
    "Match Handicap",
    "Match Result",
    "3-Way First Half Handicap",
    "1st Half Result",
    "3-Way First Quarter Handicap",
    "1st Quarter Result",
    "1st Half Money Line and 1st Half Total Points Over/Under",
    "1st Quarter Money Line and 1st Quarter Total Points Over/Under",
    "Money Line and Total Points Over/Under (Including Overtime)",
    "2nd Half Money Line",
    "1st Quarter Race To 10 Points",
    "1st Quarter Race To 15 Points",
    "1st Quarter Race To 5 Points",
    "2nd Half Result",
    "2nd Quarter Race To 10 Points",
    "2nd Quarter Race To 15 Points",
    "2nd Quarter Race To 5 Points",
    "2nd Quarter Result",
    "3-Way Fourth Quarter Handicap",
    "3-Way Second Half Handicap",
    "3-Way Second Quarter Handicap",
    "3-Way Third Quarter Handicap",
    "3rd Quarter Race To 10 Points",
    "3rd Quarter Race To 15 Points",
    "3rd Quarter Race To 5 Points",
    "3rd Quarter Result",
    "4th Quarter Race To 10 Points",
    "4th Quarter Race To 15 Points",
    "4th Quarter Race To 5 Points",
    "4th Quarter Result",
    "Double Chance",
    "First Half Double Chance",
    "First Quarter Double Chance",
    "Fourth Quarter Double Chance",
    "Second Half Double Chance",
    "Second Quarter Double Chance",
    "Third Quarter Double Chance",
    "Last Team To Score"
];